version: '3'
services:
  product-category-app:
    container_name: product-category-app
    image: murugesh1996/mmv2-productcategory:0.0.2-SNAPSHOT
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - docker-mysql
    environment:
      NAMING_SERVER: http://naming-server:8761/eureka
      WAIT_HOSTS: mysql:3306
      RDS_PORT: "3306"

  docker-mysql:
    container_name: docker-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_ROOT_PASSWORD: ecommerceapp
      MYSQL_ROOT_HOST: '%'
    volumes:
      - docker-mysql:/var/lib/mysql
      - ./ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql
    ports:
      - "6666:3306"
    healthcheck:
      test: ["CMD", "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 30s

volumes:
  docker-mysql:
